version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always

  app-python:
    build: ./app-python
    depends_on:
      - redis

  app-node:
    build: ./app-node
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - cache_data:/var/cache/nginx
    ports:
      - "80:80"
    depends_on:
      - app-python
      - app-node

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  cache_data:
