proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;

server {
    listen 80;

    # App 1 - Cache de 10 segundos
    location /app1/ {
        proxy_cache my_cache;
        proxy_cache_valid 200 10s;
        proxy_pass http://app-python:5001/;
        add_header X-Cache-Status $upstream_cache_status;
    }

    # App 2 - Cache de 1 minuto
    location /app2/ {
        proxy_cache my_cache;
        proxy_cache_valid 200 60s;
        proxy_pass http://app-node:5002/;
        add_header X-Cache-Status $upstream_cache_status;
    }
}

# Endpoint de métricas para Observabilidade
server {
    listen 8080;
    location /nginx_status {
        stub_status on;
        access_log off;
    }
}